import Head from 'next/head'
import { Heading, Text } from '@ignite-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading as="h1">Hello world</Heading>
    </>
  )
}
